js {
  const {
      simpleDimSchema,
      createOrReplaceTable
  } = require('includes/schema.js');

  const dimEntitySource = 'Category';

}

config {
    type: 'view',
    assertions: {
        uniqueKey: ['id'],
        nonNull: ['id', 'name']
    },
    tags: ['staging', 'view', 'dim']
}


SELECT
  DISTINCT ${dimEntitySource}Id AS id,
  ${dimEntitySource} AS name,
FROM
  ${ref('statistics_pre_click')}
